---
- hosts: local-dev
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true
  remote_user: administrator
  become: true
  become_method: sudo
  roles:
    - common
    - odoo
    - postgresql
    - wkhtmltopdf
    - nginx
